This is a testharness.js-based test.
PASS Same-origin syntax error
PASS Same-origin throw
FAIL Cross-origin syntax error assert_throws_dom: function "function() {
    importScripts(crossOrigin +
                  "/workers/modules/resources/syntax-error.js");
  }" threw null, not an object
FAIL Cross-origin throw assert_throws_dom: function "function() {
    importScripts(crossOrigin +
                  "/workers/modules/resources/throw.js");
  }" threw null, not an object
PASS Redirect-to-cross-origin syntax error
PASS Redirect-to-Cross-origin throw
Harness: the test ran to completion.

